pipeline {
    agent any

    environment {
        ANSIBLE_HOST = 'ec2-user@ec2-13-50-101-159'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Microservices') {
            steps {
                sh '''
                    echo "Build des services un par un"
                    cd Excellia_bourse
                    sudo chown -R jenkins:jenkins /var/lib/jenkins/workspace/Excellia-bourse-pipeline

                    for service in discovery-service config-service gateway-service utilitiesService gestion-bourse-candidature-service inscription-service messagerie-service notification-service; do
                        echo "Build du service: $service"
                        cd $service
                        mvn clean package -DskipTests
                        cd ..
                    done
                '''
            }
        }

        stage('Déploiement sur EC2 avec Ansible') {
            steps {
                sh '''
                    ANSIBLE_BECOME_USER=root ansible-playbook -i localhost, /var/lib/jenkins/workspace/Excellia-bourse-pipeline/deployment/ansible/deploy.yml -c local -b --become-method=sudo -e "ansible_become_password="
                '''
            }
        }
    }
}
